### ISSUE TITLE
Object.require is deprecated.

### ISSUE THREAD

**Issue by MarekZ98** [Peekmo/atom-autocomplete-php#409]
Use `remote.Dialog` instead of `remote.require("dialog")`
```
Object.require (C:\Users\marek\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:64:12)
Object.<anonymous> (C:\Users\marek\.atom\packages\plantuml-generator\lib\file-utils.coffee:8:19)
Object.<anonymous> (C:\Users\marek\.atom\packages\plantuml-generator\lib\file-utils.coffee:64:4)
Object.<anonymous> (C:\Users\marek\.atom\packages\plantuml-generator\lib\file-utils.coffee:68:3)
Module._compile (<embedded>:11:147429)
Object..coffee (<embedded>:11:150977)
```

**Comment by kigyousensi** [comment]
I have same issue on Ubuntu 20.10 + Atom 1.53.0

Use remote.dialog instead of remote.require("dialog")
Object.require - /usr/share/atmo/rewources/aspp.asar/src/electron-shims.js:4:12
Object.require  <anonynous> -/home/<ID>/..atom/packages/plantuml/file-utils.coffee:8:19
Object.require  <anonynous> -/home/<ID>/..atom/packages/plantuml/file-utils.coffee:64:4
Object.require  <anonynous> -/home/<ID>/..atom/packages/plantuml/file-utils.coffee:68:3
Module._compile - <embedded>:11:147498
Object.coffee - <emvedded>:11:151046

There is the path " /usr/share/atmo/rewources/aspp.asar/src/electron-shims.js" in line 2.
but "/usr/share/atmo/rewources/aspp.asar/" is not directory. it's file.
