### ISSUE TITLE
Still can't make it work

### ISSUE THREAD

**Issue by alexandernst** [Peekmo/atom-autocomplete-php#80]
I have been following this package for quite some time now. A few months ago I opened a bug report about not being able to make it work (show anything).

I just tried it again and I still can't make it work (can't make it output anything at all).

I'm using a composer project (which is detected very nicely by Intellij IDEA). I even see the package doing *things* in the dev console (messages like "Building index"), but I don't see any popups with an autocomplete.

I even tried https://github.com/Peekmo/atom-autocomplete-php/pull/78 and it doesn't show any warnings, which confirms that my project is alright. 

Is there anything I can do to make this plugin tell me why is it not working? Is there some "verbose/debug" mode?

**Comment by hotoiledgoblinsack** [comment]
Hello

These are some things I noticed that can cause problems (disclaimer: I'm not a core developer, more of a user and minor contributor):
  * When a syntax error is present in a file being saved, autocompletion can stop working.
  * IIRC the package requires that the project follows the PSR-2 standard with relation to naming classes, methods, and so on (maybe @Peekmo can confirm this).
  * Not every corner case works yet, but simple `$this->` autocompletion should work fine (*inside* class method definitions).
  * Are you sure the classmap and autoload.php paths in your configuration are set to the correct location (relative to your project root)?
  * Is there actually any content in the `autoload_classmap.php` file or is it just an empty array? If it is empty, I believe you can forcibly fill it using `composer dumpautoload -o`. It should be automatically filled by Composer but I've found that with some `composer.json` configurations it is not.

AFAIK there is no verbose switch, but if you are familiar with the developer tools of Chromium (as for building websites), you can also use that in Atom by viewing the package source, placing 'debugger' statements in the CoffeeScript code and then refreshing your PHP project using Ctrl+R with the developer tools open (or just use the Chromium Debugger to manually place breakpoints). You can use this to examine output from PHP and see what the code is doing as a last resort. (It requires no additional software or anything.)

Hope this helps.

**Comment by Peekmo** [comment]
Hello,

@hotoiledgoblinsack has list every thing that could be a problem for the plugin (thank you).

Anyway, can you try to clone this repo : https://github.com/hotoiledgoblinsack/php-autocomplete-test and (after a composer install), for example, in this file, at this line : https://github.com/hotoiledgoblinsack/php-autocomplete-test/blob/master/src/TestNamespace/SomeBaseClass.php#L52 write $this->

If something is showed, then, the problem is from your project.

Regards,
Peekmo

**Comment by alexandernst** [comment]
Will try to test all this tomorrow, I have been extremely busy those days. Sorry for the delay.

**Comment by alexandernst** [comment]
Ok, tested the repo you linked and indeed, the autocomplete worked. I must debug my project and find where/why it's failing.

**Comment by alexandernst** [comment]
Btw, will this plugin work with PSR-4?

**Comment by Peekmo** [comment]
Hello,

Yes, I'm following PSR-4 in all my projects, and it works

**Comment by alexandernst** [comment]
Ok, let's give this another angle. I'm using this project with Yii2, so let me see if I can create an empty Yii2 project and make this plugin work.

**Comment by Peekmo** [comment]
I just tried Yii2 framework.

The plugin does not support this framework for a simple reason : This framework does not rely on composer for its autoloading at all (no section 'autoload' in its composer.json and see vendor/yiisoft/yii2/Yii.php).

So, sorry, but it will never be supported (at least for PHP5, I have better hopes for PHP7) in this plugin.

**Comment by alexandernst** [comment]
I'm not really sure how/what you tested, but here is what I see/do:

    composer global require "fxp/composer-asset-plugin:~1.0.3"
    composer create-project --prefer-dist yiisoft/yii2-app-basic basic

This creates the folder `basic` that contains a new Yii2 project. The `composer.json` file at the root folder is supposed to be edited by the developer and fill in the fields related to the project (name, version, etc).

The folder `vendor` contains (among others) a folder called `yiisoft`, which contains the Yii2 structure. The file `yii2/composer.json` contains an `autoload` section (which is what you're looking for).

Yii2 itself is using composer, as all Yii2's plugins and external libraries. Why I can't get autocomplete when using Yii2 if composer is used?

**Comment by Peekmo** [comment]
The composer.json in the root folder in the one that download all vendors (like Yii), and they have all a composer.json. But if the project would be managed with composer, you'll have a section "autoload" with your personal source files in a composer.json. But there is not. There's a section "autoload" with Yii vendor source code in ```yii2/composer.json``` but not your source files (backend, common, console, ...)

Play the command ```composer dump-autoload``` in your project and have a look into ```vendor/composer/autoload_classmap.php``` and you'll see that there's an empty array... So the main composer doesn't manage the autoloading of your sources, just those of your vendors (check to write $this-> in a yii2 vendor's class, it should work.

**Comment by alexandernst** [comment]
So this plugin is actually able to work with Yii2, it's just that it's missing a little bit of glue when there is no autoload section in the "main" composer.json file.

Would it be difficult to make this plugin scan the vendors folder and try to "manually" load what it can?

Also, is this plugin just relying on the content of the autoload_classmap.php or is there some more composer-related magic happening behind the curtains?

**Comment by Peekmo** [comment]
Yes, it will be difficult because it needs an autoloader to be able to work with PHP reflection (the plugin does not parse all PHP files), and the composer classmap to easily find all files. The classmap could be done manually, but not the autoloader. Moreover, the plugin parse the autoload section of your composer to add the right namespace to your files.

**Comment by alexandernst** [comment]
Sorry for insisting, but aside from the "autoload" section in the main composer.json file I can't really see any difference between a new symfony project (with which this plugin works) and a new yii2 project (with which this plugin doesn't work).

This is how a new symfony project looks like: http://ibin.co/2GjuJSCR6MoN

And this is how a new yii2 project looks like: http://ibin.co/2Gjutz1sSigI

So, both projects have autoload_(classmap, files, namespaces, psr4) and all of them are filled with the (I assume) correct namespaces, files, paths and so on. So, aside from the "autoload" section, there isn't really any other difference. Hence, why Symfony is working, but Yii2 isn't?

I'm sorry for being repetitive, but I just can't really understand where exactly is the problem.

**Comment by Peekmo** [comment]
The autoload section is the most important.
If you see a symfony2 project, you have something like that in the autoload section ```"psr-4": { "": "src/" }```
It tells to composer ```every classes under src are prefix by nothing``` and so, in autoload_namespaces, ```""```will match ```.../src``` So, the class files within ```src``` folder will be autoloaded by composer.

In this plugin, we require in the proxy (https://github.com/Peekmo/atom-autocomplete-php/blob/master/php/parser.php#L80) an autoloader (composer ones by default) to be able to find every classes by reflection in PHP. If your source files (like in Yii2) are not autoloaded by composer, when we try to do a reflection on it, it fails, because the script doesn't know your class, because we didn't require it.

You could try to add ```vendor/yiisoft/yii2/Yii.php``` in the configuration of the plugin (section "Autoloader file"), 'cause it seems to be the main autoloader of Yii2, but even if it's partially works, you will miss some features because the autoload_classmap will not contains your source files.

**Comment by alexandernst** [comment]
As far as I know (perhaps I read it somewhere in Yii's docs) Yii2 uses [spl_autoload_register](http://php.net/manual/en/function.spl-autoload-register.php). Basically, it tells composer that it will use it's own class mapper/importer/loader, but iirc composer is still able to understand and work with that. Not sure if that help somehow.

**Comment by Peekmo** [comment]
spl_autoload_register doesn't tell anything to composer. It's a PHP feature, used by composer itself (in vendor/composer/autoload_real.php) It just tell PHP that "When this class is instanciated, look into those files".

**Comment by bboure** [comment]
This is an old issue, but hare are my findings.
In my case, Yii's clases would be indexed correctly (because of [this](https://github.com/yiisoft/yii2/blob/master/composer.json#L98)) but it would not load my personal classes...

So, I just added this to my composer.json (assuming that `app` is my root namespace).

````json
    "autoload": {
        "psr-4": {"app\\": ""}
    }
````

Dont' forget to  `composer dump-autoload`

You might also need to restart Atom to force a reindexing (By the way @Peekmo , we are missing a command for that)

I am still not sure what impact it can have on the autoloading on the project itself. But if you follow [Yii's recommendations](http://www.yiiframework.com/doc-2.0/guide-concept-autoloading.html#using-other-autoloaders) it should be good.

> When using the Yii autoloader together with other autoloaders, you should include the Yii.php file after all other autoloaders are installed. This will make the Yii autoloader the first one responding to any class autoloading request.

atom-autocomplete-php would then use psr-4 from composer to autoload/parse the project, but when the project is running, it would still be using Yii's autoloader.

**Comment by bboure** [comment]
Oh, @alexandernst I just saw you other issue here: https://github.com/Peekmo/atom-autocomplete-php/issues/124
which is basically what I just explained :)
