### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by alexandernst** [Peekmo/atom-autocomplete-php#9]
Hi @Peekmo ! I have a few questions regarding this plugin :)

* `it will only works for composer projects` -> do you plan adding adding support for files outside of a composer project? I mean, sometimes I tend to create a small set of files somewhere in `/tmp` just to test something. It would be nice if this plugin could work with that usage case too.

* `the autocompletion for 'new Class()' is currently disabled because I'm working on it` -> do you mean that in the future you'll support autocomplete on objects from external classes, not part of PHP's set of classes?

* will you support showing the output of methods in the autocomplete? I mean, if I have something like `$mathObj->`, I'd expect the autocomplete to show the following:

```
    f        className()        string
    f        sum($a, $b)        int
    f        square($a, $b)     int
    p        max_int            int
    p        min_int            int
```

`f` stands for "function" (could be `m` for "method" too) and `p` stands for "property". On the right side is shown the returned data type.

Keep the good work! ;)

**Comment by Peekmo** [comment]
Hello,
> do you plan adding adding support for files outside of a composer project? I mean, sometimes I tend to create a small set of files somewhere in /tmp just to test something. It would be nice if this plugin could work with that usage case too.

That's not plan for the moment because it's really hard. You'll have some bases (php defined classes and functions), local variables, but nothing more for the moment. Why ? Because the plugin rely on an autoloader and the composer's classmap to build suggestions. With an unknown project structure, that's really difficult.

> the autocompletion for 'new Class()' is currently disabled because I'm working on it -> do you mean that in the future you'll support autocomplete on objects from external classes, not part of PHP's set of classes?

Yes. The works is already done, but for large project it was too slow, so I'm working on a little index for this purpose (see #8)

> will you support showing the output of methods in the autocomplete? I mean, if I have something like $mathObj->, I'd expect the autocomplete to show the following [...]

Yes, it's planned for the first release (see #6) It will be outputed to the left, because that's how autocomplete-plus works, and I prefer to keep the same behavior between my providers and other autocomplete-plus's one.

Regards,
Peekmo

**Comment by alexandernst** [comment]
Great! I'll be watching this project! Really good work, impressive!

Regards
